# Generated by Django 3.0.8 on 2020-07-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200729_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coca',
            name='image',
            field=models.ImageField(upload_to='cocacola/media/portfolio/images/'),
        ),
    ]
